### ISSUE TITLE
Unable to upload more than 1 image to media

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#979] opened 2020-08-11 07:05 UTC
When editing a node, if you try to upload more than one image you get the following message:

Error File already exists at path: 33/27/98/627488ca535ca64cb36b1ec144621d2d41c20ce3.jpg

**Comment by rchavik** [comment] 2020-08-12 13:19
Please check that you are not uploading a previously uploaded file.

**Comment by slightlychilled** [comment] 2020-08-12 13:39
Uploading the same file with a different file name should work? Yes or No?

**Comment by rchavik** [comment] 2020-08-13 01:13
> Uploading the same file with a different file name should work? Yes or No?

No. It hashes the file content and use it as filename

**Comment by rchavik** [comment] 2020-10-05 05:41
Closing since this is by design

**Closed by rchavik** 2020-10-05 05:41 UTC
