### ISSUE TITLE
Error in dashboard on the enable Croogo / Comments plugin

### ISSUE THREAD

**Issue by maiconpinto** [croogo/croogo#811] opened 2017-03-30 18:14 UTC
I try croogo (3.0) when I enable Croogo/Comments show error in Dashboard:

> Cell class Cell is missing.

Before:

`/home/maiconpinto/croogo/vendor/croogo/croogo/Dashboards/src/Template/Element/admin/dashboard.ctp
`
```php
$cell = $this->cell($dashboard['cell'], $dashboard['arguments'],
    ['cache' => $dashboard['cache'], 'alias' => $alias, 'dashboard' => $dashboard]); ?>
<?= $cell; ?>
```

After fixed:

```php
 if (!empty($dashboard['cell'])) {
    $cell = $this->cell($dashboard['cell'], $dashboard['arguments'],
        ['cache' => $dashboard['cache'], 'alias' => $alias, 'dashboard' => $dashboard]); 
    
    echo $cell;
}

if (!empty($dashboard['element'])) {
    $element = $this->element($dashboard['element'], $dashboard['arguments'],
        ['cache' => $dashboard['cache'], 'alias' => $alias, 'dashboard' => $dashboard]); 
    
    echo $element;
}
?>
```

**Comment by rchavik** [comment] 2017-03-31 05:21
Sorry, I can't reproduce this issue.
Can you retry with latest commit?

**Comment by maiconpinto** [comment] 2017-03-31 13:05
Thank you fixed issue #810 , I run composer update and receive this update, but when I click em Dashboard, show error:

![screenshot from 2017-03-31 09-33-02](https://cloud.githubusercontent.com/assets/1476940/24550617/3f47603e-15f5-11e7-8573-a0ad89be9049.png)

Probably this error happens because the config of Croogo/Example, in Example/config/admin_dashboard.php, doesn't have the key cell in your $config. 
So in Dashboard.admin/dashboard doesn't have how to show elements, only cells.

```php
<div class="card card-<?php echo $alias; ?> dashboard-card" id="<?php echo $alias ?>">
    <div class="card-header">
        <i class="fa fa-list move-handle"></i>
        <?php echo $dashboard['title'] ?>
        <a class="toggle-icon float-right" data-toggle="collapse" data-target="#<?php echo $alias ?>-content">
            <?php echo($dashboard['collapsed'] ? '<i class="fa fa-plus"></i>' : '<i class="fa fa-minus"></i>') ?>
        </a>
    </div>
    <div class="card-block <?= $dashboard['collapsed'] ? 'collapse' : 'collapse show' ?>" id="<?php echo $alias ?>-content">
        <?php $cell = $this->cell($dashboard['cell'], $dashboard['arguments'],
            ['cache' => $dashboard['cache'], 'alias' => $alias, 'dashboard' => $dashboard]); ?>
        <?= $cell; ?>
    </div>
</div>
```
My suggestion is above. I'm not an expert developer, but I would like to help this project, and learning more with the best cakephp developers.  :+1:

**Comment by rchavik** [comment] 2017-03-31 13:29
ah, `Croogo/Example` plugin.

**Comment by maiconpinto** [comment] 2017-03-31 13:37
Sorry, I had said Croogo/Comments, but in this case is Croogo/Example.

**Comment by rchavik** [comment] 2017-03-31 14:47
Should be fixed now

**Closed by rchavik** 2017-03-31 14:47 UTC
