### ISSUE TITLE
2.2 Croogo Cake Bake Controller Template

### ISSUE THREAD

**Issue by ionas** [croogo/croogo#632] opened 2015-03-18 16:21 UTC
Following is a controller bake template output after modification of the translation strings.
Previously they did target the ```__d('croogo', ...)``` and thus all the plugin specific strings went there.

```php
<?php
App::uses('FlexitariffsAppController', 'Flexitariffs.Controller');
/**
 * TariffGroupOptionKeys Controller
 *
 * @property TariffGroupOptionKey $TariffGroupOptionKey
 * @property PaginatorComponent $Paginator
 */
class TariffGroupOptionKeysController extends FlexitariffsAppController {

/**
 * Components
 *
 * @var array
 */
	public $components = array('Paginator');

/**
 * admin_index method
 *
 * @return void
 */
	public function admin_index() {
		$this->TariffGroupOptionKey->recursive = 0;
		$this->set('tariffGroupOptionKeys', $this->paginate());
	}

/**
 * admin_view method
 *
 * @throws NotFoundException
 * @param string $id
 * @return void
 */
	public function admin_view($id = null) {
		if (!$this->TariffGroupOptionKey->exists($id)) {
			throw new NotFoundException(__d('croogo', 'Invalid %s', __d('flexitariffs', 'tariff group option key')));
		}
		$options = array('conditions' => array('TariffGroupOptionKey.' . $this->TariffGroupOptionKey->primaryKey => $id));
		$this->set('tariffGroupOptionKey', $this->TariffGroupOptionKey->find('first', $options));
	}

/**
 * admin_add method
 *
 * @return void
 */
	public function admin_add() {
		if ($this->request->is('post')) {
			$this->TariffGroupOptionKey->create();
			if ($this->TariffGroupOptionKey->save($this->request->data)) {
				$this->Session->setFlash(__d('croogo', 'The %s has been saved', __d('flexitariffs', 'tariff group option key')), 'default', array('class' => 'success'));
				$this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__d('croogo', 'The %s could not be saved. Please, try again.', __d('flexitariffs', 'tariff group option key')), 'default', array('class' => 'error'));
			}
		}
		$trackableCreators = $this->TariffGroupOptionKey->TrackableCreator->find('list');
		$trackableUpdaters = $this->TariffGroupOptionKey->TrackableUpdater->find('list');
		$this->set(compact('trackableCreators', 'trackableUpdaters'));
	}

/**
 * admin_edit method
 *
 * @throws NotFoundException
 * @param string $id
 * @return void
 */
	public function admin_edit($id = null) {
		if (!$this->TariffGroupOptionKey->exists($id)) {
			throw new NotFoundException(__d('croogo', 'Invalid tariff group option key'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->TariffGroupOptionKey->save($this->request->data)) {
				$this->Session->setFlash(__d('croogo', 'The %s has been saved', __d('flexitariffs', 'tariff group option key')), 'default', array('class' => 'success'));
				$this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__d('croogo', 'The %s could not be saved. Please, try again.', __d('flexitariffs', 'tariff group option key')), 'default', array('class' => 'error'));
			}
		} else {
			$options = array('conditions' => array('TariffGroupOptionKey.' . $this->TariffGroupOptionKey->primaryKey => $id));
			$this->request->data = $this->TariffGroupOptionKey->find('first', $options);
		}
		$trackableCreators = $this->TariffGroupOptionKey->TrackableCreator->find('list');
		$trackableUpdaters = $this->TariffGroupOptionKey->TrackableUpdater->find('list');
		$this->set(compact('trackableCreators', 'trackableUpdaters'));
	}

/**
 * admin_delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param string $id
 * @return void
 */
	public function admin_delete($id = null) {
		$this->TariffGroupOptionKey->id = $id;
		if (!$this->TariffGroupOptionKey->exists()) {
			throw new NotFoundException(__d('croogo', 'Invalid %s', __d('flexitariffs', 'tariff group option key')));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->TariffGroupOptionKey->delete()) {
			$this->Session->setFlash(__d('croogo', '%s deleted.', __d('flexitariffs', 'Tariff group option key')), 'default', array('class' => 'success'));
			$this->redirect(array('action' => 'index'));
		}
		$this->Session->setFlash(__d('croogo', 'The %s was not deleted.', __d('flexitariffs', 'Tariff group option key')), 'default', array('class' => 'error'));
		$this->redirect(array('action' => 'index'));
	}
}

**Comment by ionas** [comment] 2015-03-18 16:21
Do you think this is a good approach? any suggestions?
I will also try to modify the bake templates to respect "Apply" vs "Save"

**Comment by ionas** [comment] 2015-03-18 16:38
The Apply feature would simply add this to the templates:

```php
/// edit
			$redirectTo = array('action' => 'index');
			if (isset($this->request->data['apply'])) {
				$redirectTo = array('action' => 'edit', $id);
			}
// add
			$redirectTo = array('action' => 'index');
			if (isset($this->request->data['apply'])) {
				$redirectTo = array('action' => 'add');
			}
```

**Comment by ionas** [comment] 2015-03-18 20:00
@rchavik if you think this make sense I ll prepare another PR.

**Comment by rchavik** [comment] 2015-03-19 02:23
Yes.  This is desirable.

One comment for `add`, I think in `apply` mode, it should redirect to edit action with the newly saved id.

**Comment by jhli** [comment] 2015-03-19 07:53
Add apply redirecting to add apply allows to add a lot of data smoothly.

**Comment by rchavik** [comment] 2015-03-19 08:49
@jhli, You think so?  I would think that behavior would be counter intuitive compared to existing feature.

I think we can change "Save" to "Save and add another" or  just add a new button for this function if really desired.  Comments?

**Comment by jhli** [comment] 2015-03-19 09:02
I think the expected behavior of apply is ambigious. Some magento shot: http://posextension.com/wp-content/uploads/2014/04/how-to-add-new-product-attributes-in-magento-step-3-1024x412.png

**Comment by ionas** [comment] 2015-03-19 09:44
The following make sense imho:
* **Save & Continue Edit** (works for both, new and edit views, to me feels a bit strange on add views)
* **Save and New** (saves and redirects back to new, feels a bit strange on edit views)
* **Save** (saves and redirects back to index)
* **Reset** (just the html browser functionality)
* **Back** (not required cause it usually easy to get to the index views)

**Comment by rchavik** [comment] 2015-03-19 09:51
I guess I chose "Apply" due to the default dialog buttons `Ok`, `Apply`, and `Cancel`.  And it's short.  "Save and Continue Edit" is too long.

In any case, I don't think we should change the label now. Let's just add "Save & New" ?

**Comment by ionas** [comment] 2015-03-19 09:55
While I am not deep into Croogo development, I do agree that it is bad to change the common interface in some minor release. Adding Save & New sounds good to me. So apply would always go to the records (edit or add -> edit) and Save & New would always go to add.
Should Save & New also be rendered on edit actions/views?

**Comment by ionas** [comment] 2015-03-19 10:00
Should default translation domain be "default" or "croogo" if it is no plugin.

**Comment by ionas** [comment] 2015-03-19 10:42
PR: https://github.com/croogo/croogo/pull/633

**Comment by jhli** [comment] 2015-04-22 15:43
Closing as https://github.com/croogo/croogo/pull/634 is opened and merged.

**Closed** 2015-04-22 15:44 UTC
