### ISSUE TITLE
custom fields 

### ISSUE THREAD

**Issue by cocosuma** [croogo/croogo#851] opened 2018-01-03 13:16 UTC
Hi,

I installed Croogo 3.0.2 and adding custom field is not working anymore.

Request URL:http://croogo/admin/meta/meta/add-meta
Request Method:GET
Status Code:500 Internal Server Error
 
I have the following error in my logs : 

2018-01-03 14:09:36 Error: [Cake\View\Exception\MissingLayoutException] Layout file "Admin\Layout\ajax.ctp" is missing.
Exception Attributes: array (
  'file' => 'Admin\\Layout\\ajax.ctp',
)
Request URL: /admin/meta/meta/add-meta
Referer URL: http://croogo/admin/nodes/nodes/edit/7
Stack Trace:
#0 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\View\View.php(794): Cake\View\View->_getLayoutFileName('ajax')
#1 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\View\View.php(770): Cake\View\View->renderLayout('', 'ajax')
#2 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Controller\Controller.php(623): Cake\View\View->render(NULL, NULL)
#3 C:\wamp64\www\comparer-demenager\vendor\croogo\croogo\Core\src\Controller\AppController.php(112): Cake\Controller\Controller->render(NULL, NULL)
#4 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(125): Croogo\Core\Controller\AppController->render()
#5 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(Croogo\Meta\Controller\Admin\MetaController))
#6 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\wamp64\www\comparer-demenager\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\wamp64\www\comparer-demenager\vendor\cakephp\cakephp\src\Http\Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\wamp64\www\comparer-demenager\webroot\index.php(40): Cake\Http\Server->run()
#19 {main}

thanks for your help

**Comment by rchavik** [comment] 2018-01-04 04:55
I wasn't able to reproduce this issue locally and in https://demo.croogo.org/3.0

How did you install croogo?

**Comment by cocosuma** [comment] 2018-01-04 13:42
Hello 
install it with composer. i've also made yesterday a fresh install with composer too  and the issue is the same

**Comment by rchavik** [comment] 2018-01-05 08:14
Can you verify that you have `C:\wamp64\www\comparer-demenager\src\Template\Layout\ajax.ctp`

I don't use windows so I can't investigate this.

**Comment by rchavik** [comment] 2018-01-16 06:24
I have just encountered a similar issue but it was due to the logged in user not granted access to the ajax action.

In your case, it seems to be /admin/meta/meta/add-meta, so check that your user has been granted access to that action.

**Comment by rchavik** [comment] 2018-01-19 13:41
Figured out the caused. Related to croogo/app@45d24eebb0980c12fa881e818681c2e9db0a48cb

Just need to figure out the fix

**Comment by rchavik** [comment] 2018-01-20 11:38
Should be fixed now in croogo/app@45d24eebb0980c12fa881e818681c2e9db0a48cb and croogo/croogo@777e1aa83132240521373688d1b308c47b4430b0

**Closed by rchavik** 2018-01-20 11:38 UTC
Labels: Defect

**Comment by cocosuma** [comment] 2018-01-20 13:33
thanks for resolving this issue
