### ISSUE TITLE
Installation: Database, version MySQL

### ISSUE THREAD

**Issue by Vadimushka** [croogo/croogo#817] opened 2017-04-21 12:26 UTC
When, I filled in the engine for hosting, performed `composer install`, then went to the site, and performed the installation, then at the stage of installation with the database of this written here: [ScreenShot](https://vk.com/doc141967230_444277365), 

I understand the error with the choice of database, because as a local host, everything was fine ... you need to fix the connection to the database ...

**Comment by rchavik** [comment] 2017-04-22 05:30
I don't understand what the problem is.

From the screenshot, it seems that the installer was not able to connect to the database.  To fix this, you need to provide the correct user/password/host/dbname/port.

**Comment by Vadimushka** [comment] 2017-04-22 17:49
Sorry, but I did.
I installed the correct data to connect to the database.
But on localhost, everything works fine.
And here on a hosting the connection with a database does not work
-----
Простите, но я так и сделал.
Я установил корретные данные для подключения к базе данных.
Но на локалхост, все отлично работает.
А вот на хостинге не работает соединение с базой данных

**Comment by rchavik** [comment] 2017-04-24 02:23
Hmm,

I will need more info on this. Is there anything else in error.log?
can you connect using plain php functions (not using cakephp)?

**Comment by dakota** [comment] 2017-05-07 10:05
Fixed in https://github.com/croogo/croogo/commit/f14b59a2ea602113d2cb99146ffd71fbec7911e2. Was due to an incorrectly named input field.

**Closed by dakota** 2017-05-07 10:05 UTC

**Comment by rchavik** [comment] 2017-05-08 02:06
how did it work with localhost? :confused:
