### ISSUE TITLE
Unable to log out on mobile devices

### ISSUE THREAD

**Issue by rakeshtembhurne** [croogo/croogo#659] opened 2015-05-24 10:18 UTC
There are some design issues due to which I am not able to click on "profile" or "Logout" link on smaller screens. I experienced this issue when using croogo site on Android 4.4 with Chrome installed. 

This issue can be replicated by starting Chrome Developer Tool and changing device mode to any mobile phone. I checked with Nexus 5.

For more clarity, attaching this video: https://www.dropbox.com/s/fwpdvm1picmcbjx/croogo_logout_error.mp4?dl=0

**Comment by rchavik** [comment] 2015-05-25 12:56
Similar/duplicate of #604.

Fix is to upgrade twbs.

**Comment by rchavik** [comment] 2020-10-05 05:29
Not reproducible now since twbs has been uppgraded.

**Closed by rchavik** 2020-10-05 05:29 UTC
Labels: Defect, Duplicate
