### ISSUE TITLE
Node.Path not updated

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#970] opened 2020-05-02 05:02 UTC
When editing the permalink on the edit node form, the slug in the database is updated, but the path is not. This leads to issues where the content link is not correct.

**Comment by rchavik** [comment] 2020-05-04 13:23
Hmm, I can't reproduce this.  What version are you using?

Note: It was a problem for < 4.0.0-beta.3. Fixed in 91b6b510552c5f0c6de4785dbe579c2110dbdb4d

**Comment by slightlychilled** [comment] 2020-08-11 06:42
now works in latest release

**Closed** 2020-08-11 06:42 UTC
